# Change these first
owner: Papinotas-Desarrollo # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Papinotas app
    url: https://papinotasapp.com/user
  - name: Papinotas Homepage
    url: https://www.papinotas.cl
assignees:
  # You can add members of your team to be assigned to every downtime issue
  - felipe-calderon-papinotas

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  theme: ocean
  cname: status.papinotasapp.com
  # baseUrl: /your-repo-name
  logoUrl: https://papinotas.cl/wp-content/uploads/2021/08/logo-papinotas.svg
  favicon: https://papinotasapp.com/favicon-16x16.png
  name: Status
  introTitle: "**Upptime** papinotas."
  introMessage: Nuestros servicios en **tiempo real**.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "*/15 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
